{
 "title": "cluster-hbase-test-hbase",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "hbase.regionserver.regionCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.regionCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.regionCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.regionCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.storeCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.storeCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.storeCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.storeCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.hlogFileCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.hlogFileCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.hlogFileCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.hlogFileCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.hlogFileSize",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.hlogFileSize",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.hlogFileSize",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.hlogFileSize",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.storeFileCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.storeFileCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.storeFileCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.storeFileCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.memStoreSize",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.memStoreSize",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.memStoreSize",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.memStoreSize",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Mutate_75th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Mutate_90th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Increment_75th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Mutate_99th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Mutate_95th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Mutate_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Increment_99th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.FlushTime_75th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.FlushTime_95th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Get_75th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Get_95th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.ScanNext_75th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_75th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.ScanNext_90th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Increment_90th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Increment_99th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Increment_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.FlushTime_90th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.FlushTime_99th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.FlushTime_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Get_90th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_90th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.Get_99th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.Get_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.ScanNext_95th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_95th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.ScanNext_99th_percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.ScanNext_99th_percentile",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.readRequestCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.readRequestCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.readRequestCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.readRequestCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.writeRequestCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.writeRequestCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.writeRequestCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.writeRequestCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.get_num_ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.get_num_ops",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.get_num_ops",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.get_num_ops",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.scanNext_num_ops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.scanNext_num_ops",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.scanNext_num_ops",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.scanNext_num_ops",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.mutateCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.mutateCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.mutateCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.mutateCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  },
  {
   "title": "hbase.regionserver.deleteCount",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.deleteCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31001", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.deleteCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31011", "job": "regionserver" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hbase.regionserver.deleteCount",
     "tags": { "cluster": "test-hbase", "hostAndPort": "127.0.0.1-31021", "job": "regionserver" }
    }
   ]
  }
 ]
}