{
 "title": "test-hdfs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "hdfs.namenode.fs.CapacityRemaining",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.fs.CapacityRemaining",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    }
   ]
  },
  {
   "title": "hdfs.namenode.fs.CapacityTotal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.fs.CapacityTotal",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    }
   ]
  },
  {
   "title": "hdfs.namenode.fs.CapacityUsed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.fs.CapacityUsed",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    }
   ]
  },
  {
   "title": "hdfs.namenode.fs.state.NumLiveDataNodes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.fs.state.NumLiveDataNodes",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.fs.state.NumDecomLiveDataNodes",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.fs.state.NumDeadDataNodes",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    }
   ]
  },
  {
   "title": "hdfs.namenode.fs.FilesTotal",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.fs.FilesTotal",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    }
   ]
  },
  {
   "title": "hdfs.namenode.fs.MissingBlocks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.fs.MissingBlocks",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    }
   ]
  },
  {
   "title": "hdfs.namenode.activity.SyncsNumOps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.activity.SyncsNumOps",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    }
   ]
  },
  {
   "title": "hdfs.namenode.activity.SyncsAvgTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.namenode.activity.SyncsAvgTime",
     "tags": { "cluster": "test-hdfs", "job": "namenode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.activity.FlushAvgTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FlushAvgTime",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FlushAvgTime",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FlushAvgTime",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.activity.FsyncAvgTime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FsyncAvgTime",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FsyncAvgTime",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FsyncAvgTime",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.activity.FlushNanosNumOps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FlushNanosNumOps",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FlushNanosNumOps",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FlushNanosNumOps",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.activity.FsyncNanosNumOps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FsyncNanosNumOps",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FsyncNanosNumOps",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.FsyncNanosNumOps",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.activity.BytesRead",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BytesRead",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BytesRead",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BytesRead",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.activity.BytesWritten",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BytesWritten",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BytesWritten",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BytesWritten",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.activity.BlocksRead",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BlocksRead",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BlocksRead",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BlocksRead",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.activity.BlocksWritten",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BlocksWritten",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BlocksWritten",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.activity.BlocksWritten",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.fs.state.Remaining",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.fs.state.Remaining",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.fs.state.Remaining",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.fs.state.Remaining",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.fs.state.Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.fs.state.Capacity",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.fs.state.Capacity",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.fs.state.Capacity",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  },
  {
   "title": "hdfs.datanode.fs.state.DfsUsed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.fs.state.DfsUsed",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21001", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.fs.state.DfsUsed",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21011", "job": "datanode" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "hdfs.datanode.fs.state.DfsUsed",
     "tags": { "cluster": "test-hdfs", "hostAndPort": "127.0.0.1-21021", "job": "datanode" }
    }
   ]
  }
 ]
}