{
 "title": "{{.Tittle}}",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "sys.mem.free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "currentTagKey": "host",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "sys.mem.free",
     "tags": { "host": "{{.HostName}}" }
    }
   ]
  },
  {
   "title": "sys.cpu.percent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "first",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "downsampleInterval": "1s",
     "metric": "sys.cpu.percent",
     "tags": { "host": "{{.HostName}}" }
    }
   ]
  },
  {
   "title": "sys.cpu.load1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "sys.cpu.load1",
     "tags": { "host": "{{.HostName}}" }
    }
   ]
  },
  {
   "title": "sys.cpu.load5",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "sys.cpu.load5",
     "tags": { "host": "{{.HostName}}" }
    }
   ]
  },
  {
   "title": "sys.cpu.load15",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "sys.cpu.load15",
     "tags": { "host": "{{.HostName}}" }
    }
   ]
  },
  {
   "title": "sys.mem.usedPercent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "sys.mem.usedPercent",
     "tags": { "host": "{{.HostName}}" }
    }
   ]
  },
  {
   "title": "sys.disk.usedPercent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "sys.disk.usedPercent./dev/nvme0n1p1",
     "tags": { "host": "{{.HostName}}" }
    }
   ]
  },
  {
   "title": "sys.net.bytesSent.lo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "sys.net.bytesSent.lo",
     "tags": { "host": "{{.HostName}}" }
    }
   ]
  },
  {
   "title": "sys.net.bytesRecv.lo",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "sys.net.bytesRecv.lo",
     "tags": { "host": "{{.HostName}}" }
    }
   ]
  }
 ]
}