{
 "title": "GC Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "node.jvm.gc.survivor0",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.survivor0.capacity",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.survivor0.usage",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  },
  {
   "title": "node.jvm.gc.survivor1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.survivor1.capacity",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.survivor1.usage",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  },
  {
   "title": "node.jvm.gc.eden",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.eden.capacity",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.eden.usage",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  },
  {
   "title": "node.jvm.gc.old.space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.old.space.capacity",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.old.space.usage",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  },
  {
   "title": "node.jvm.gc.young.gc.count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.young.gc.count",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  },
  {
   "title": "node.jvm.gc.full.gc.count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.full.gc.count",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  },
  {
   "title": "node.jvm.gc.young.gc.time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.young.gc.time",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  },
  {
   "title": "node.jvm.gc.full.gc.time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.full.gc.time",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  },
  {
   "title": "node.jvm.gc.metaspace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.metaspace.capacity",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.metaspace.usage",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  },
  {
   "title": "node.jvm.gc.compressed.class.space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.compressed.class.space.capacity",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "node.jvm.gc.compressed.class.space.usage",
     "tags": { "cluster": "test-hbase", "job": "regionserver", "task": "0" }
    }
   ]
  }
 ]
}