{
 "title": "cluster-zookeeper-test-zk",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "zookeeper.zkServer.zk_num_alive_connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_num_alive_connections",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_num_alive_connections",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_num_alive_connections",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_approximate_data_size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_approximate_data_size",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_approximate_data_size",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_approximate_data_size",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_avg_latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_avg_latency",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_avg_latency",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_avg_latency",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_min_latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_min_latency",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_min_latency",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_min_latency",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_max_latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_max_latency",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_max_latency",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_max_latency",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_outstanding_requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_outstanding_requests",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_outstanding_requests",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_outstanding_requests",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_packets_sent",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_packets_sent",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_packets_sent",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_packets_sent",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_packets_received",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_packets_received",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_packets_received",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_packets_received",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_znode_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_znode_count",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_znode_count",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_znode_count",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_watch_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_watch_count",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_watch_count",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_watch_count",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  },
  {
   "title": "zookeeper.zkServer.zk_ephemerals_count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_ephemerals_count",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10010", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_ephemerals_count",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10020", "job": "zkServer" }
    },
    {
     "aggregator": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "zookeeper.zkServer.zk_ephemerals_count",
     "tags": { "cluster": "test-zk", "hostAndPort": "127.0.0.1-10030", "job": "zkServer" }
    }
   ]
  }
 ]
}